// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReservationSystem.Infrastructure.Persistence;

#nullable disable

namespace ReservationSystem.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReservationSystem.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_date");

                    b.Property<DateTime>("SalesEndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sales_end_at");

                    b.Property<DateTime>("SalesStartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sales_start_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("EventDate")
                        .HasDatabaseName("ix_events_date");

                    b.HasIndex("VenueId")
                        .HasDatabaseName("ix_events_venue_id");

                    b.ToTable("events", null, t =>
                        {
                            t.HasCheckConstraint("ck_events_sales_before_event", "sales_end_at <= event_date");

                            t.HasCheckConstraint("ck_events_sales_window", "sales_start_at < sales_end_at");
                        });
                });

            modelBuilder.Entity("ReservationSystem.Domain.Entities.EventSeat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uuid")
                        .HasColumnName("seat_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_event_seats");

                    b.HasIndex("SeatId")
                        .HasDatabaseName("ix_event_seats_seat_id");

                    b.HasIndex("EventId", "SeatId")
                        .IsUnique()
                        .HasDatabaseName("ux_event_seats_event_seat");

                    b.HasIndex("EventId", "Status")
                        .HasDatabaseName("ix_event_seats_availability");

                    b.ToTable("event_seats", null, t =>
                        {
                            t.HasCheckConstraint("ck_event_seats_price", "price >= 0");

                            t.HasCheckConstraint("ck_event_seats_status", "status IN ('Available', 'Held', 'Sold')");
                        });
                });

            modelBuilder.Entity("ReservationSystem.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("ProviderPaymentId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_payment_id");

                    b.Property<string>("ProviderToken")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("provider_token");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_payments");

                    b.HasIndex("ProviderPaymentId")
                        .IsUnique()
                        .HasDatabaseName("ux_payments_provider_payment_id")
                        .HasFilter("provider_payment_id IS NOT NULL");

                    b.HasIndex("ProviderToken")
                        .IsUnique()
                        .HasDatabaseName("ux_payments_provider_token")
                        .HasFilter("provider_token IS NOT NULL");

                    b.HasIndex("ReservationId")
                        .IsUnique()
                        .HasDatabaseName("ux_payments_single_pending")
                        .HasFilter("status = 'Pending'");

                    b.HasIndex("ReservationId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_payments_reservation");

                    b.ToTable("payments", null, t =>
                        {
                            t.HasCheckConstraint("ck_payments_amount", "amount > 0");

                            t.HasCheckConstraint("ck_payments_completed", "(status = 'Pending') = (completed_at IS NULL)");

                            t.HasCheckConstraint("ck_payments_status", "status IN ('Pending', 'Succeeded', 'Failed', 'Abandoned')");
                        });
                });

            modelBuilder.Entity("ReservationSystem.Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTime>("HeldUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("held_until");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_reservations");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_reservations_event_id");

                    b.HasIndex("HeldUntil")
                        .HasDatabaseName("ix_reservations_expiry")
                        .HasFilter("status = 'Held'");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_reservations_user");

                    b.ToTable("reservations", null, t =>
                        {
                            t.HasCheckConstraint("ck_reservations_status", "status IN ('Held', 'Confirmed', 'Expired', 'Failed', 'Cancelled')");

                            t.HasCheckConstraint("ck_reservations_total", "total_amount >= 0");
                        });
                });

            modelBuilder.Entity("ReservationSystem.Domain.Entities.ReservationItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EventSeatId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_seat_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal>("PriceAtReservation")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price_at_reservation");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.HasKey("Id")
                        .HasName("pk_reservation_items");

                    b.HasIndex("EventSeatId")
                        .IsUnique()
                        .HasDatabaseName("ux_reservation_items_active_seat")
                        .HasFilter("is_active = true");

                    b.HasIndex("ReservationId")
                        .HasDatabaseName("ix_reservation_items_reservation");

                    b.ToTable("reservation_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_reservation_items_price", "price_at_reservation >= 0");
                        });
                });

            modelBuilder.Entity("ReservationSystem.Domain.Entities.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("RowLabel")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("row_label");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("integer")
                        .HasColumnName("seat_number");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.HasKey("Id")
                        .HasName("pk_seats");

                    b.HasIndex("VenueId", "RowLabel", "SeatNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_seats_venue_position");

                    b.ToTable("seats", null, t =>
                        {
                            t.HasCheckConstraint("ck_seats_number", "seat_number > 0");
                        });
                });

            modelBuilder.Entity("ReservationSystem.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_role", "role IN ('User', 'Admin')");
                        });
                });

            modelBuilder.Entity("ReservationSystem.Domain.Entities.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("city");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_venues");

                    b.ToTable("venues", (string)null);
                });

            modelBuilder.Entity("ReservationSystem.Domain.Entities.Event", b =>
                {
                    b.HasOne("ReservationSystem.Domain.Entities.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_events_venues_venue_id");
                });

            modelBuilder.Entity("ReservationSystem.Domain.Entities.EventSeat", b =>
                {
                    b.HasOne("ReservationSystem.Domain.Entities.Event", "Event")
                        .WithMany("EventSeats")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_seats_events_event_id");

                    b.HasOne("ReservationSystem.Domain.Entities.Seat", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_seats_seats_seat_id");

                    b.Navigation("Event");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("ReservationSystem.Domain.Entities.Payment", b =>
                {
                    b.HasOne("ReservationSystem.Domain.Entities.Reservation", null)
                        .WithMany("Payments")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_reservations_reservation_id");
                });

            modelBuilder.Entity("ReservationSystem.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("ReservationSystem.Domain.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reservations_events_event_id");

                    b.HasOne("ReservationSystem.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reservations_users_user_id");
                });

            modelBuilder.Entity("ReservationSystem.Domain.Entities.ReservationItem", b =>
                {
                    b.HasOne("ReservationSystem.Domain.Entities.EventSeat", null)
                        .WithMany()
                        .HasForeignKey("EventSeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reservation_items_event_seats_event_seat_id");

                    b.HasOne("ReservationSystem.Domain.Entities.Reservation", null)
                        .WithMany("Items")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reservation_items_reservations_reservation_id");
                });

            modelBuilder.Entity("ReservationSystem.Domain.Entities.Seat", b =>
                {
                    b.HasOne("ReservationSystem.Domain.Entities.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_seats_venues_venue_id");
                });

            modelBuilder.Entity("ReservationSystem.Domain.Entities.Event", b =>
                {
                    b.Navigation("EventSeats");
                });

            modelBuilder.Entity("ReservationSystem.Domain.Entities.Reservation", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
